Repository yujeong-ran/mallan, pull requests merged in 2025-06, with the labels that each got.

#42 [#40] 배포 관련 파일 수정 및 데이터베이스 변경
  backend/.gitignore
  backend/build.gradle
  backend/docker-compose.yml
  backend/src/main/resources/application-deploy.yml
  backend/src/main/resources/application-local.yml
Labels: feature, fix

#48 [#47] CORS 설정 수정
  backend/src/main/java/com/mallan/yujeongran/config/SecurityConfig.java
  backend/src/main/java/com/mallan/yujeongran/config/WebMvcConfig.java
Labels: fix

#50 [#49] CORS 설정 수정
  backend/src/main/java/com/mallan/yujeongran/config/SecurityConfig.java
Labels: fix

#56 [#52] 라이어 게임 - 게임 시작 전 방 설정 기능 구현
  frontend/src/api/createPlayerApi.ts
  frontend/src/api/getTopicApi.ts
  frontend/src/api/roomJoinApi.ts
  frontend/src/api/selectRoomRoundApi.ts
  frontend/src/api/selectRoomTopicApi.ts
  frontend/src/components/common/CharacterSet.tsx
  frontend/src/components/liar/GameSetCon.tsx
  frontend/src/pages/liar/LiarRoomPage.tsx
Labels: feature

#60 [#59] 라이어 게임 - (게임 시작 전) 방 퇴장 기능 구현
  frontend/src/api/roomExitApi.ts
  frontend/src/components/common/CharacterSet.tsx
  frontend/src/components/common/gameTitle/LiarGameTitle.tsx
  frontend/src/components/liar/GameSetCon.tsx
  frontend/src/components/liar/PlayerListTabCon.tsx
Labels: feature

#68 [#67] 필터링 및 검색 기능 추가
  backend/src/main/java/com/mallan/yujeongran/icebreaking/review/controller/ReviewController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/review/dto/request/ReviewFilterRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/review/repository/ReviewRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/review/service/ReviewService.java
Labels: feature

#70 [#69] 리뷰 필터링 기능 및 페이징 구현
  backend/src/main/java/com/mallan/yujeongran/common/model/PagedResponse.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/review/controller/ReviewController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/review/repository/ReviewRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/review/service/ReviewService.java
Labels: feature, refactor
