Repository yujeong-ran/mallan, pull requests merged in 2025-05, with the labels that each got.

#3 [#1] 라이어게임 - 최초 진입 및 게임 시작 전까지의 동작 구현
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/mallan/yujeongran/MallanApplication.java
  src/main/java/com/mallan/yujeongran/common/error/ErrorCode.java
  src/main/java/com/mallan/yujeongran/common/exception/MallanCustomException.java
  src/main/java/com/mallan/yujeongran/common/exception/NotFoundTopicException.java
  src/main/java/com/mallan/yujeongran/common/handler/GlobalExceptionHandler.java
  src/main/java/com/mallan/yujeongran/common/model/ErrorResponse.java
  src/main/java/com/mallan/yujeongran/config/RedisConfig.java
  src/main/java/com/mallan/yujeongran/config/SecurityConfig.java
  src/main/java/com/mallan/yujeongran/config/SwaggerConfig.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarPlayerController.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarRoomController.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarTopicController.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarWordController.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/CreateLiarRoomRequestDto.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/CreateLiarTopicRequestDto.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/CreateLiarWordRequestDto.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/CreatePlayerRequestDto.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/ExitLiarRoomRequestDto.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/JoinLiarRoomRequestDto.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/SelectTopicRequestDto.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/response/LiarTopicResponseDto.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/response/LiarWordResponseDto.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/entity/LiarPlayer.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/entity/LiarRoom.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/entity/LiarTopic.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/entity/LiarWord.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/repository/LiarRoomRepository.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/repository/LiarTopicRepository.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/repository/LiarWordRepository.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/scheduler/RoomCleanupScheduler.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarRedisService.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarRoomService.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarTopicService.java
  src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarWordService.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feature, setting

#7 [#6] 게임방 설정 이후 기능 구현
  backend/.gradle/8.12/executionHistory/executionHistory.bin
  backend/.gradle/8.12/executionHistory/executionHistory.lock
  backend/.gradle/8.12/fileHashes/fileHashes.bin
  backend/.gradle/8.12/fileHashes/fileHashes.lock
  backend/.gradle/8.12/fileHashes/resourceHashesCache.bin
  backend/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  backend/.gradle/file-system.probe
  backend/.idea/gradle.xml
  backend/.idea/misc.xml
  backend/src/main/java/com/mallan/yujeongran/common/exception/DuplicateJoinException.java
  backend/src/main/java/com/mallan/yujeongran/common/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/mallan/yujeongran/common/model/CommonResponse.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarPlayerController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarRoomController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/response/LiarGameResultResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/response/LiarHostVerifyResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/entity/LiarRoom.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarRedisService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarRoomService.java
Labels: feature

#9 [#8] 사용자 생성시 Redis에 프로필 이미지 값 할당
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/mallan.iml
  .idea/prettier.xml
  backend/.gitignore
  backend/.gradle/8.12/executionHistory/executionHistory.bin
  backend/.gradle/8.12/executionHistory/executionHistory.lock
  backend/.gradle/8.12/fileHashes/fileHashes.bin
  backend/.gradle/8.12/fileHashes/fileHashes.lock
  backend/.gradle/8.12/fileHashes/resourceHashesCache.bin
  backend/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  backend/.gradle/file-system.probe
  backend/.idea/gradle.xml
  backend/.idea/misc.xml
  backend/.idea/vcs.xml
  backend/src/main/java/com/mallan/yujeongran/common/profile_image/avatar_1_140x140.png
  backend/src/main/java/com/mallan/yujeongran/common/profile_image/avatar_2_140x140.png
  backend/src/main/java/com/mallan/yujeongran/common/profile_image/avatar_3_140x140.png
  backend/src/main/java/com/mallan/yujeongran/common/profile_image/avatar_4_140x140.png
  backend/src/main/java/com/mallan/yujeongran/config/WebMvcConfig.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarPlayerController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/CreateLiarRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/CreateLiarTopicRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/CreateLiarWordRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/CreatePlayerRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/ExitLiarRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/JoinLiarRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/SelectTopicRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/entity/LiarPlayer.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarRedisService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarRoomService.java
Labels: feature, refactor, fix, setting

#10 [#2] 라이어 게임 - 홈 화면 구현
  frontend/index.html
  frontend/package.json
  frontend/public/font/HakgyoNadeuriB.woff2
  frontend/public/font/HakgyoNadeuriL.woff2
  frontend/public/font/JejuDoldam.woff2
  frontend/src/App.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/HomeList.tsx
  frontend/src/components/layout/HomeLayout.tsx
  frontend/src/components/layout/LiarGameLayout.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/liar/LiarMainPage.tsx
  frontend/src/styles/breakPoint.ts
  frontend/src/styles/font.css
  frontend/src/styles/gameThemes.ts
  frontend/src/styles/globalStyle.tsx
  frontend/yarn.lock
Labels: design

#13 [#12] 밸런스 게임 관련 기본 기능 구현
  backend/.gitignore
  backend/.gradle/8.12/checksums/checksums.lock
  backend/.gradle/8.12/executionHistory/executionHistory.bin
  backend/.gradle/8.12/executionHistory/executionHistory.lock
  backend/.gradle/8.12/fileChanges/last-build.bin
  backend/.gradle/8.12/fileHashes/fileHashes.bin
  backend/.gradle/8.12/fileHashes/fileHashes.lock
  backend/.gradle/8.12/fileHashes/resourceHashesCache.bin
  backend/.gradle/8.12/gc.properties
  backend/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  backend/.gradle/buildOutputCleanup/cache.properties
  backend/.gradle/buildOutputCleanup/outputFiles.bin
  backend/.gradle/file-system.probe
  backend/.gradle/vcs-1/gc.properties
  backend/src/main/java/com/mallan/yujeongran/common/profile_image/avatar_1_140x140.png
  backend/src/main/java/com/mallan/yujeongran/common/profile_image/avatar_2_140x140.png
  backend/src/main/java/com/mallan/yujeongran/common/profile_image/avatar_3_140x140.png
  backend/src/main/java/com/mallan/yujeongran/common/profile_image/avatar_4_140x140.png
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/controller/BalanceGameController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/controller/BalanceQuestionController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/controller/BalanceRoomController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/controller/BalanceTopicController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/request/CreateBalancePlayerRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/request/CreateBalanceQuestionRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/request/CreateBalanceRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/request/CreateBalanceTopicRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/request/JoinBalanceRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/request/StartBalanceGameRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/request/SubmitBalanceAnswerRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/request/UpdateBalanceQuestionCountRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/request/UpdateBalanceTopicRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/response/BalanceFinalResultResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/response/BalanceQuestionResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/response/BalanceRoomResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/dto/response/BalanceTopicResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/entity/BalanceAnswer.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/entity/BalancePlayer.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/entity/BalanceQuestion.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/entity/BalanceResult.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/entity/BalanceRoom.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/entity/BalanceTopic.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/repository/BalanceAnswerRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/repository/BalancePlayerRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/repository/BalanceQuestionRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/repository/BalanceResultRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/repository/BalanceRoomRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/repository/BalanceTopicRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/service/BalanceGameService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/service/BalancePlayerService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/service/BalanceQuestionService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/service/BalanceRoomService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/balance_game/service/BalanceTopicService.java
  backend/src/main/resources/application.yml
Labels: feature, setting

#18 [#16] 라이어게임 - 대기방 화면 구현
  frontend/public/font/.gitkeep
  frontend/public/image/select_arw.svg
  frontend/src/App.tsx
  frontend/src/components/HomeList.tsx
  frontend/src/components/common/CharacterSet.tsx
  frontend/src/components/liar/GameSetCon.tsx
  frontend/src/components/liar/PlayerListTabCon.tsx
  frontend/src/pages/.gitkeep
  frontend/src/pages/liar/LiarRoomPage.tsx
  frontend/src/styles/globalStyle.tsx
Labels: design

#20 [#19] 라이어 게임 - 대기방 정보 및 방 생성/참가 로직 수정
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarPlayerController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarRoomController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarTopicController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/controller/LiarWordController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/CreateLiarWordRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarCanStartRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarCreatePlayerWithRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarCreateRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarCreateTopicRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarCreateWordRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarEndGameRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarExitRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarGuessRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarHostVerifyRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarIsLiarRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarJoinRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarSearchPlayerWordRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarSelectTopicRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarUpdateRoundRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/request/LiarVoteRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/response/LiarHostVerifyResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/response/LiarPlayerInfoResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/dto/response/LiarWaitingRoomResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/scheduler/LiarRoomCleanupScheduler.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarPlayerService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarRoomService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarTopicService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/liar_game/service/LiarWordService.java
Labels: feature, refactor

#23 [#21] 라이어 게임 - 발언 단계 화면 구현
  frontend/src/App.tsx
  frontend/src/components/liar/Explanation.tsx
  frontend/src/components/liar/GameRuleList.tsx
  frontend/src/components/liar/StepGuide.tsx
  frontend/src/components/liar/Timer.tsx
  frontend/src/pages/liar/LiarExplanationPage.tsx
  frontend/src/styles/gameThemes.ts
Labels: design

#27 [#25] 오픈 퀘스천 뽑기 게임 - 전체 기능 구현
  backend/src/main/java/com/mallan/yujeongran/MallanApplication.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/controller/QuestionGameController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/controller/QuestionRoomController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/request/QuestionCreateRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/request/QuestionEndGameRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/request/QuestionExitRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/request/QuestionGameStartRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/request/QuestionJoinRoomRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/request/QuestionRestartGameRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/request/QuestionSelectAnswererRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/request/QuestionSetQuestionCountRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/request/QuestionSetTopicRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/request/QuestionSubmitAnswerRequestDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionCreateRoomResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionCurrentQuestionStateResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionDrawResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionExitRoomResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionJoinRoomResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionPlayerRoleResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionSelectablePlayerListResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionSelectablePlayerResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionSetQuestionCountResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionSetTopicResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/entity/QuestionHistory.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/entity/QuestionPlayer.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/entity/QuestionQuestion.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/entity/QuestionRoom.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/entity/QuestionTopic.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/repository/QuestionPlayerRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/repository/QuestionQuestionRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/repository/QuestionRoomRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/repository/QuestionTopicRepository.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/scheduler/QuestionRoomCleanupScheduler.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/service/QuestionGameService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/service/QuestionRoomService.java
Labels: feature

#29 [#28] 오픈 퀘스천 게임 - 대기방 정보 및 사용자 역할 관련 기능 구현 및 개선
  backend/src/main/java/com/mallan/yujeongran/config/SecurityConfig.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/controller/QuestionGameController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/controller/QuestionRoomController.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionPlayInfoResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/dto/response/QuestionWaitingRoomResponseDto.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/service/QuestionGameService.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/service/QuestionRoomService.java
Labels: feature, refactor

#33 [#32] 테이블 명을 재정의
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/entity/QuestionHistory.java
  backend/src/main/java/com/mallan/yujeongran/icebreaking/question_game/entity/QuestionTopic.java
Labels: refactor

#37 [#35] 라이어 게임 - 제시어 추측 입력 단계 화면 구현
  frontend/src/App.tsx
  frontend/src/pages/liar/LiarWordEnter.tsx
  frontend/src/styles/gameThemes.ts
Labels: design

#39 [#36] 배포 관련 파일 수정
  backend/src/main/resources/application-deploy.yml
Labels: feature

#41 [#40] 배포 관련 파일 수정
  backend/.dockerignore
  backend/Dockerfile
  backend/docker-compose.yml
  backend/src/main/resources/application.yml
Labels: fix
